const GH='https://github.com/lbalamurugan-185?tab=repositories';
const DL=['Overview','Business Problem','Dataset','Data Cleaning','Data Analysis','Dashboard','Insights','Recommendations'];
const SL=DL.map((x,i)=>i==5?'Query Explorer':x);
const PROJECTS=[
{id:'aerohome',t:'AeroHome Manufacturing Analytics Dashboard',c:'Power BI / Manufacturing Analytics',f:['powerbi','dashboards'],tools:['Power BI','Power Query','DAX','Data Modeling'],img:'images/aerohome-dashboard.png',
d:'Built a manufacturing analytics dashboard using a 12-table dataset transformed into a star schema. The dashboard provides insights into production output, defect rate, downtime and supplier delays.',
k:[['Defect Rate','1.69%'],['Production Achievement','96.35%'],['Total Produced','970K'],['Total Downtime','122K'],['Supplier Delay','16.55%']],
s:['An executive overview of production, quality, downtime and supply chain performance across AeroHome plants, with slicers for plant, supplier, product and date.','Leadership needs one view of how each plant performs on output, defects and downtime, and which suppliers delay deliveries.','12 related tables covering plants, products, suppliers, production and purchasing, remodelled into a star schema.','Shaped and standardised tables in Power Query. Blank supplier values show up as "(Blank)" in the supplier charts and are worth reviewing.','DAX measures for Defect Rate %, Production Achievement %, total produced units, total downtime and Supplier Delay %.','KPI cards, plant comparison charts, a production trend over time, and supplier delay and purchase spend charts.','The Coimbatore plant shows the highest downtime, defective units and output of the four plants. Precision Motors has the highest supplier delay %. Production trend drops sharply in the final months, so data completeness should be checked.','Focus downtime reduction on the highest-downtime plants, review delayed suppliers, and validate the latest period of data.']},
{id:'freshmart',t:'FreshMart Sales & Business Performance Dashboard',c:'Excel / Sales Analytics',f:['excel','dashboards'],tools:['Excel','PivotTables','Slicers','Power Query'],img:'images/freshmart-dashboard.png',
d:'Created an interactive retail sales dashboard to analyze sales, profitability, customers, orders, channels and returns.',
k:[['Sales','₹28.95L'],['Profit','₹7.37L'],['Profit Margin','25.47%'],['Orders','2,500'],['Customers','700']],
s:['An interactive Excel dashboard covering sales, profit, customers, orders, channels and returns for a retail business.','Management needs one view of sales and profit by channel, membership tier, category and region, including returns.','Retail transactions: 2,500 orders from 700 customers, with payment, channel, store and membership details.','Cleaned and combined tables with Power Query, fixed data types and checked blanks (a blank region appears in the regional chart).','Calculated Sales, Profit, Profit Margin (Profit ÷ Sales), Orders and Customers with PivotTables, then compared channel, membership, weekday/weekend and category performance.','Excel dashboard with slicers for payment mode, sales channel and return status, plus trend, pie, column and regional charts.','In-Store drives 71% of sales. Gold members contribute the most sales of the membership tiers. The South region leads regional sales.','Grow Online and Mobile App share, move Silver members toward Gold, and focus promotions and stock on top categories and the South region.']},
{id:'trendkart',t:'TrendKart Fashion Sales Analysis',c:'Excel / Fashion Analytics',f:['excel','dashboards'],tools:['Excel','Power Query','PivotTables'],img:'images/trendmart-dashboard.png',
d:'Analyzed 3,000 transaction records across six tables and identified a 30.6% monthly sales decline.',
k:[['Total Sales','₹92.27L'],['Total Profit','₹18.01L'],['Profit Margin','19.52%'],['Avg Discount','12.57%']],
s:['Analysis of 3,000 transaction records across six tables covering sales trend, profit, discounts, returns, channels, states and categories.','Understand the monthly sales decline and how discounts, returns and channel mix affect profit.','3,000 transaction records across six related tables, including store and invoice details.','Combined the six tables with Power Query, standardised fields and validated keys.','PivotTable analysis of sales and profit trend, discount bands, returns, Online vs Offline, state and category performance.','Dashboard with Invoice Year and Discount % slicers and charts for each analysis area.','Monthly sales declined 30.6%. Offline stores generate roughly two-thirds of sales, and the 0% discount band has the highest sales.','Review discount policy by band, investigate the decline by state and category, and grow the Online channel.']},
{id:'novatech',t:'NovaTech Manufacturing & Supply Chain Dashboard',c:'Power BI / Supply Chain',f:['powerbi','dashboards'],tools:['Power BI','Data Modeling','Power Query','DAX'],
d:'Built a Power BI analytics solution using 3,600+ production runs and 1,600 purchase orders to analyze defects, downtime, energy usage and supplier delays.',
k:[['Production Runs','3,600+'],['Purchase Orders','1,600']],
s:['A Power BI solution covering production, supplier, downtime and defect performance.','Operations needs visibility into defects, downtime, energy usage and supplier delays across production and purchasing.','3,600+ production runs and 1,600 purchase orders.','Power Query transformations and a data model relating production and purchasing facts.','DAX measures for defects, downtime, energy usage and supplier delay.','KPI cards with production, supplier, downtime and defect analysis views.','The analysis shows where defects, downtime and supplier delays concentrate across lines and suppliers.','Prioritise downtime and defect reduction on the worst-performing lines, and manage chronically late suppliers through performance reviews.']},
{id:'healthplus',t:'HealthPlus Healthcare Database Analysis',c:'SQL / Healthcare',f:['sql'],tools:['MySQL','SQL'],L:SL,ti:5,
d:'A 5-table relational healthcare database analysed with joins, GROUP BY, aggregate and window functions, and ranking.',k:[],
s:['A 5-table relational healthcare database in MySQL, queried for healthcare analytics.','Turn raw healthcare records into answers about patients, doctors and visits.','Five related tables linked through primary and foreign keys.','Defined keys and data types; checked for duplicates and nulls.','SQL joins, GROUP BY, aggregate functions, window functions and ranking.','Pick a concept below to see the query pattern.','Window functions and ranking make it easy to compare records within groups.','Add indexes and views for frequently run reports.'],
tabs:[['Joins','-- Illustrative pattern; table and column names are examples\nSELECT p.name, d.name AS doctor\nFROM visits v\nJOIN patients p ON p.id = v.patient_id\nJOIN doctors d ON d.id = v.doctor_id;',1],['GROUP BY','SELECT department, COUNT(*) AS visits\nFROM visits\nGROUP BY department;',1],['Aggregates','SELECT AVG(cost) AS avg_cost, MAX(cost) AS max_cost\nFROM treatments;',1],['Ranking','SELECT doctor_id, COUNT(*) AS visits,\n  RANK() OVER (ORDER BY COUNT(*) DESC) AS rnk\nFROM visits\nGROUP BY doctor_id;',1]]},
{id:'medicare',t:'MediCare Healthcare Database Analysis',c:'SQL / Healthcare',f:['sql'],tools:['MySQL','SQL'],L:SL,ti:5,
d:'Healthcare database covering hospitals, doctors, appointments, specializations and consultation fees, analysed with ranking and LAG.',k:[],
s:['A healthcare database in MySQL covering hospitals, doctors, appointments, specializations and consultation fees.','Answer analytical questions on doctors, appointments and fees across hospitals and specializations.','Tables for hospitals, doctors, appointments, specializations and consultation fees.','Defined keys and data types; checked for duplicates and nulls.','Joins, fee aggregations, ranking and the LAG function for period-over-period comparison.','Pick a concept below to see the query pattern.','Ranking and LAG turn raw appointment and fee rows into comparisons.','Add views for common reports such as fees by specialization.'],
tabs:[['Joins','-- Illustrative pattern; table and column names are examples\nSELECT h.name, d.name AS doctor, s.title\nFROM doctors d\nJOIN hospitals h ON h.id = d.hospital_id\nJOIN specializations s ON s.id = d.spec_id;',1],['Consultation fees','SELECT s.title, AVG(d.fee) AS avg_fee\nFROM doctors d JOIN specializations s ON s.id = d.spec_id\nGROUP BY s.title;',1],['Ranking','SELECT name, fee,\n  DENSE_RANK() OVER (ORDER BY fee DESC) AS fee_rank\nFROM doctors;',1],['LAG','SELECT month, appointments,\n  LAG(appointments) OVER (ORDER BY month) AS prev_month\nFROM monthly_appointments;',1]]},
{id:'rag',t:'Context-Aware Learning Assistant using RAG',c:'GenAI / RAG',f:['genai','python'],tools:['Python','FastAPI','React','FAISS','Sentence Transformers','LangChain','Gemini API'],
d:'Built a Retrieval-Augmented Generation learning assistant that retrieves relevant educational resources and generates context-aware answers.',k:[],flow:1,ti:3,
L:['Overview','Problem','Solution','RAG Architecture (click a step)','Features','Voice Interaction (STT / TTS)'],
s:['A learning assistant that retrieves relevant educational resources and generates context-aware answers.','Plain chatbots can answer without grounding; learners need answers tied to relevant study material.','Retrieval-Augmented Generation: retrieve the most relevant content first, then let the LLM answer from it.','','Semantic retrieval over educational resources, grounded answers, FastAPI REST endpoints and a React interface.','Speech-to-text for asking questions and text-to-speech for spoken answers.'],
tabs:[['Documents','Educational resources are the knowledge source.'],['Document Chunking','Documents are split into smaller chunks that can be matched to a question.'],['Embeddings','Sentence Transformers turn each chunk into a vector.'],['FAISS Vector Database','Vectors are stored in a FAISS index for fast similarity search.'],['Semantic Retrieval','The question is embedded and the closest chunks are retrieved.'],['LLM','Retrieved context and the question go to the Gemini API via LangChain.'],['Grounded Answer','The assistant returns an answer based on the retrieved material.']]}
];
