(()=>{const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const LI='https://www.linkedin.com/in/lbalamurugan-15/',EM='lbalamurugan185@gmail.com',RS='resume/Balamurugan_L_Resume.pdf';
const home=!!$('#home'),P=home?'':'index.html';
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const nav=[['Home',P||'#home'],['About',P+'#about'],['Skills',P+'#skills'],['Projects','projects.html'],['Experience',P+'#experience'],['Certifications',P+'#certifications'],['Resume',P+'#resume'],['Contact',P+'#contact']];
document.body.insertAdjacentHTML('afterbegin',`<div id=prog></div><a class=skip href=#main>Skip to content</a><header id=nav><div class="wrap bar"><a class=logo href="${nav[0][1]}">Bala<b>Murugan</b></a><nav id=menu aria-label=Primary>${nav.map(([n,h])=>`<a href="${h}">${n}</a>`).join('')}</nav><button id=theme class=ic aria-label="Toggle dark or light mode">◐</button><a class="btn p sm vp" href=projects.html>View Projects</a><button id=burger class=ic aria-label=Menu aria-expanded=false>☰</button></div></header>`);
document.body.insertAdjacentHTML('beforeend',`<footer><div class="wrap fg"><div><h3>BALAMURUGAN L</h3><p class=lead>Data Analyst | Business Intelligence</p></div><div><h4>Quick Links</h4><a href=projects.html>Projects</a><a href="${RS}">Resume</a><a href="${LI}" target=_blank rel="noopener noreferrer">LinkedIn</a><a href="https://github.com/lbalamurugan-185" target=_blank rel="noopener noreferrer">GitHub</a><a href="mailto:${EM}">Email</a></div></div><p class="wrap copy">© 2026 Balamurugan L. All rights reserved.</p></footer><button id=top class=ic aria-label="Back to top" hidden>↑</button>`);
if(!home)$('#menu a[href="projects.html"]').setAttribute('aria-current','page');
const root=document.documentElement;
$('#theme').onclick=()=>{const t=root.dataset.theme=='dark'?'light':'dark';root.dataset.theme=t;try{localStorage.t=t}catch(e){}};
const mn=$('#menu'),bg=$('#burger');bg.onclick=()=>bg.setAttribute('aria-expanded',mn.classList.toggle('open'));
mn.onclick=e=>{if(e.target.tagName=='A'){mn.classList.remove('open');bg.setAttribute('aria-expanded',false)}};
const tp=$('#top');tp.onclick=()=>scrollTo({top:0});
addEventListener('scroll',()=>{const h=root.scrollHeight-innerHeight;$('#prog').style.transform=`scaleX(${h>0?scrollY/h:0})`;$('#nav').classList.toggle('sc',scrollY>10);tp.hidden=scrollY<600},{passive:true});
function count(el){const n=+el.dataset.n,d=+el.dataset.d||0,s=el.dataset.s||'',t0=performance.now();const f=t=>{const k=Math.min((t-t0)/1200,1);el.textContent=(n*(1-Math.pow(1-k,3))).toFixed(d)+s;if(k<1)requestAnimationFrame(f)};requestAnimationFrame(f)}
const io=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;e.target.classList.add('in');if(e.target.classList.contains('cnt'))count(e.target);io.unobserve(e.target)}),{threshold:.15});
const reveal=()=>$$('.rv:not(.in),.cnt:not(.in)').forEach(el=>io.observe(el));reveal();
if(home){const links=$$('#menu a');new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.toggleAttribute('aria-current',a.getAttribute('href')=='#'+e.target.id))}),{rootMargin:'-45% 0px -50% 0px'}).observe&&$$('main section[id]').forEach(s=>{new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>{const on=a.getAttribute('href')=='#'+s.id;on?a.setAttribute('aria-current','true'):a.removeAttribute('aria-current')})}),{rootMargin:'-45% 0px -50% 0px'}).observe(s)})}
// project cards + modal
const tags=a=>a.map(t=>`<span>${esc(t)}</span>`).join('');
window.projectCard=p=>`<article class="card pc rv">${p.img?`<img src="${p.img}" alt="${esc(p.t)} preview" loading=lazy>`:`<div class=ph>${esc(p.t.split(' ')[0])}<small>Dashboard preview coming soon</small></div>`}<div class=pb><span class=eye>${esc(p.c)}</span><h3>${esc(p.t)}</h3><p>${esc(p.d)}</p><div class=tags>${tags(p.tools)}</div><div class=acts><button class="btn p sm" data-case="${p.id}">View Case Study</button><a class="btn sm" href="${p.gh||GH}" target=_blank rel="noopener noreferrer">GitHub</a>${p.demo?`<a class="btn sm" href="${p.demo}" target=_blank rel="noopener noreferrer">Live Demo</a>`:''}</div></div></article>`;
window.reveal=reveal;
const dlg=document.createElement('dialog');dlg.setAttribute('aria-labelledby','dt');document.body.append(dlg);let last;
dlg.addEventListener('click',e=>{if(e.target===dlg||e.target.closest('[data-x]'))dlg.close()});
dlg.addEventListener('close',()=>{document.body.style.overflow='';last&&last.focus()});
window.openCase=(id,b)=>{const p=PROJECTS.find(x=>x.id==id);if(!p)return;last=b;const L=p.L||DL;let h='';
const kp=p.k.length?`<h3>Key KPIs</h3><div class=kp style="grid-template-columns:repeat(auto-fit,minmax(130px,1fr))">${p.k.map(([a,b])=>`<div><b>${esc(b)}</b><span>${esc(a)}</span></div>`).join('')}</div>`:'';
const tb=p.tabs?`<div class="tabs ${p.flow?'flow':''}" role=group aria-label="Interactive explorer">${p.tabs.map(t=>`<button class=tb aria-pressed=false>${esc(t[0])}</button>`).join('')}</div><div class=tout aria-live=polite></div>`:'';
p.s.forEach((x,i)=>{h+=`<h3>${L[i]}</h3>${x?`<p>${esc(x)}</p>`:''}`;if(i==(p.ti??5))h+=tb;if(i==5)h+=kp});
dlg.innerHTML=`<div class=md><button class="ic x" data-x aria-label="Close case study (Esc)" autofocus>✕</button><span class=eye>${esc(p.c)}</span><h2 id=dt>${esc(p.t)}</h2>${p.img?`<img src="${p.img}" alt="${esc(p.t)} dashboard">`:''}${h}<h3>Technology Stack</h3><div class=tags>${tags(p.tools)}</div><div class=acts style="margin-top:20px"><a class="btn p sm" href="${p.gh||GH}" target=_blank rel="noopener noreferrer">GitHub</a>${p.demo?`<a class="btn sm" href="${p.demo}" target=_blank rel="noopener noreferrer">Live Demo</a>`:''}<button class="btn sm" data-x>Close</button></div></div>`;
if(p.tabs){const o=$('.tout',dlg),bs=$$('.tb',dlg),sel=i=>{bs.forEach((x,j)=>x.setAttribute('aria-pressed',j==i));const [,t,c]=p.tabs[i];o.innerHTML=c?`<pre><code>${esc(t)}</code></pre>`:`<p>${esc(t)}</p>`};bs.forEach((x,i)=>x.onclick=()=>sel(i));sel(0)}
dlg.showModal();document.body.style.overflow='hidden'};
document.addEventListener('click',e=>{const b=e.target.closest('[data-case]');if(b)openCase(b.dataset.case,b)});
// home-only
const fe=$('#fgrid');if(fe){fe.innerHTML=['aerohome','freshmart','rag'].map(i=>projectCard(PROJECTS.find(p=>p.id==i))).join('');reveal()}
const sk=$('#sk');if(sk){const SK={'Data Analytics':[['SQL','Query, join and aggregate relational data.','sql'],['Excel','PivotTables, slicers and interactive dashboards.','excel'],['Power BI','Data models, DAX measures and interactive reports.','power bi'],['Tableau','Visual analytics and BI dashboards.','tableau','Certification: Tableau BI Analyst Professional Certificate'],['Python','Data handling and AI application development.','python'],['Data Cleaning','Standardising and validating raw data.','power query'],['Data Visualization','Turning numbers into clear visuals.','dashboards'],['Business Intelligence','KPIs and dashboards that support decisions.','dashboards']],
Programming:[['Python','Data handling and AI application development.','python'],['JavaScript','Interactivity for web interfaces.','javascript','Used in this portfolio'],['HTML','Semantic page structure.','html','Used in this portfolio'],['CSS','Responsive, accessible styling.','css','Used in this portfolio']],
Databases:[['MySQL','Relational databases and analytical SQL.','mysql'],['PostgreSQL','Open-source relational database.','postgres'],['MongoDB','Document-oriented NoSQL database.','mongo']],
'AI / GenAI':[['RAG','Grounding LLM answers in retrieved documents.','rag'],['FAISS','Vector similarity search.','faiss'],['Sentence Transformers','Text embeddings for semantic search.','sentence'],['LangChain','Orchestrating LLM pipelines.','langchain'],['FastAPI','Python REST APIs.','fastapi'],['Generative AI','LLM-powered applications.','gemini']],
Tools:[['Git','Version control.','git','Used for this portfolio'],['GitHub','Code hosting and collaboration.','github','Hosts this portfolio'],['VS Code','Code editor.','vscode'],['Figma','Interface design and prototyping.','figma'],['REST APIs','Endpoints between front end and back end.','fastapi']]};
const tabs=$('#skt'),chips=$('#skc'),sp=$('#sp');
const show=(s,b)=>{$$('.chip').forEach(x=>x.setAttribute('aria-pressed',x==b));const re=new RegExp('\\b'+s[2],'i'),rel=PROJECTS.filter(p=>re.test(p.tools.join(' ')+' '+p.f.join(' ')+' '+p.c+' '+p.t));
sp.innerHTML=`<h3>${esc(s[0])}</h3><p class=lead>${esc(s[1])}</p><div class=dots role=img aria-label="Used in ${rel.length} of ${PROJECTS.length} projects">${PROJECTS.map((_,i)=>`<i class="${i<rel.length?'f':''}"></i>`).join('')}</div><p class=lead>${rel.length?`Used in ${rel.length} of ${PROJECTS.length} projects`:'No listed project yet'}${s[3]?'. '+esc(s[3]):''}</p><div class=rel>${rel.map(p=>`<button class="btn sm" data-case="${p.id}">${esc(p.t.split(' ')[0])}</button>`).join('')}</div>`};
const pick=k=>{$$('.tb',tabs).forEach(x=>x.setAttribute('aria-pressed',x.textContent==k));chips.innerHTML=SK[k].map((s,i)=>`<button class=chip aria-pressed=false data-i=${i}>${esc(s[0])}</button>`).join('');sp.innerHTML='<p class=lead>Hover or click a skill to see what it is and where I used it.</p>';
$$('.chip',chips).forEach(c=>{const f=()=>show(SK[k][c.dataset.i],c);c.onclick=f;c.onmouseenter=f;c.onfocus=f})};
tabs.innerHTML=Object.keys(SK).map(k=>`<button class=tb aria-pressed=false>${k}</button>`).join('');tabs.onclick=e=>{if(e.target.classList.contains('tb'))pick(e.target.textContent)};pick('Data Analytics')}
const cf=$('#cf');if(cf)cf.onsubmit=e=>{e.preventDefault();const f=new FormData(cf);location.href=`mailto:${EM}?subject=${encodeURIComponent(f.get('subject'))}&body=${encodeURIComponent(f.get('message')+'\n\nFrom: '+f.get('name')+' ('+f.get('email')+')')}`};
})();
